src/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('password-change/', views.PasswordChangeView.as_view(),
         name='password-change'),
    path('password-reset/', views.PasswordResetView.as_view(),
         name='password-reset'),
    path('password-reset-done/', views.PasswordResetDoneView.as_view(),
         name='password-reset-done'),
    path('password-reset/<uuid:uidb64>/<slug:token>/',
         views.PasswordResetConfirmView.as_view(),
         name='password-reset-confirm'),
]

src/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'
urlpatterns = [
    path('me/', views.ShowProfile.as_view(), name='show_self'),
    path('me/edit/', views.EditProfile.as_view(), name='edit_self'),
    path('<slug:slug>/', views.ShowProfile.as_view(),
         name='show'),
]

src/tours/urls.py
from django.urls import path
from . import views

app_name = "tours"
urlpatterns = [
    path('', views.ShowTours.as_view(), name='tours'),
    path('create_tour', views.TourCreate.as_view(), name='create_tour'),
    path('<int:pk>/', views.TourDetail.as_view(), name='tour'),
    path('<int:pk>/reserve', views.make_reserve, name='reserve'),
    path('<int:pk>/delete', views.TourDelete.as_view(), name='delete'),
    path('<int:pk>/edit', views.TourEdit.as_view(), name='edit')
]

src/templates/_brandname.html
Sao Luis Tour

src/templates/_navbar.html
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">About</a></li>
<li {% if active_link == "tours" %}class="active"{% endif %}><a href="{% url 'tours:tours' %}">Tours</a></li>

src/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

{% block navbar-right %}
{% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
{% else %}
{{ block.super }}
{% endif %}
{% endblock %}

{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>{% include "_brandname.html" %}</h1>
        <p class="lead">The best tours</p>
      </div>
    </div>
  </div>
</div>

{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
{% endblock scripts %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
   {% load staticfiles %}
   {% load thumbnail %}

   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="description" content="{% block description %}{% endblock description %}">
      <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

      <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

      <!-- Bootstrap core CSS -->
      <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

      <!-- Custom styles for this site -->
      {% block styles %}
      <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
      {% endblock styles %}

      <!-- Custom tags for the head tag -->
      {% block extrahead %}{% endblock extrahead %}

      <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!--[if lt IE 9]>
         <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
         <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
      <![endif]-->
   </head>

   <body>

      {% block navbar %}
      <div class="navbar navbar-default" role="navigation">
         <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
               <span class="sr-only">Toggle navigation</span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">
               {% block navbar-brand %}
               <img src="{% static 'site/img/logo.png' %}" alt="logo">
               {% include "_brandname.html" %}
               {% endblock %}
            </a>
         </div>
         {% block navbar-menu %}
         <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
               {% block navbar-left %}{% endblock %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
               {% block navbar-right %}
               {% if user.is_authenticated %}
               {% if user.is_staff %}
               {# <li><a href="{% url 'admin:index' %}">Admin</a></li> #}
               {% endif %}
               <li class="dropdown">
                  <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
                     <img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
                     {{ user.get_full_name|truncatechars:20 }}
                     <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                     <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                     <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
               </li>
               {% endif %}
               {% endblock %}
            </ul>
            </ul>
         </div><!--/.nav-collapse -->
         {% endblock %}
      </div>
      {% endblock navbar %}

      {% block messages %}
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">  <!-- singular -->
         <a class="close" data-dismiss="alert">×</a>
         {{ message|safe }}
      </div>
      {% endfor %}
      {% endif %}
      {% endblock %}

      {% block splash %}
      {% endblock splash %}

      {% block container %}
      <div class="container">
      </div>
      {% endblock container %}

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
      <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
      {% block scripts %}
      {% endblock scripts %}
   </body>
</html>

src/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block navbar-left %}
{% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
{% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
{% else %}
{{ block.super }}
{% endif %}
{% endblock %}

{% block messages %}
{{ block.super }}
{% endblock %}

{% block container %}
<div class="container">
   <div class="row">
      <div class="col-md-8 col-sm-8">
         <h1>{% include "_brandname.html" %}</h1>
         {% if not user.is_authenticated %}
         <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up for Free!</a>
         {% endif %}
      </div>
      <div class="col-md-4 col-sm-4">

      </div>
   </div>
</div>
{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}