src/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('password-change/', views.PasswordChangeView.as_view(),
         name='password-change'),
    path('password-reset/', views.PasswordResetView.as_view(),
         name='password-reset'),
    path('password-reset-done/', views.PasswordResetDoneView.as_view(),
         name='password-reset-done'),
    path('password-reset/<uuid:uidb64>/<slug:token>/',
         views.PasswordResetConfirmView.as_view(),
         name='password-reset-confirm'),
]

src/tours/urls.py
from django.urls import path
from . import views

app_name = "tours"
urlpatterns = [
    path('', views.ShowTours.as_view(), name='tours'),
    path('create_tour', views.TourCreate.as_view(), name='create_tour'),
    path('<int:pk>/', views.TourDetail.as_view(), name='tour'),
    path('<int:pk>/reserve', views.make_reserve, name='reserve'),
    path('<int:pk>/delete', views.TourDelete.as_view(), name='delete'),
    path('<int:pk>/edit', views.TourEdit.as_view(), name='edit')
]

src/tours/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model

class Place(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True)

    def __str__(self):
        return f"Place: {self.name}"

class Tour(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True)
    value_adult = models.DecimalField(decimal_places=2, max_digits=10)
    value_children = models.DecimalField(decimal_places=2, max_digits=10)
    pub_date = models.DateField(auto_now_add=True)
    begin_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    places = models.ManyToManyField(Place, blank=True, related_name="tour_places")
    #destination = models.CharField(max_length=50)

    def __str__(self):
        return f"Tour: {self.name}"

    def get_absolute_url(self):
        return reverse('tour', kwargs={'pk':self.id})

src/tours/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views import generic
from django.views.generic import edit
from django.contrib import messages
from django.urls import reverse_lazy

from .models import Tour
from profiles.models import Profile
from .scrap import get_flights

class ShowTours(generic.ListView):
    template_name = 'tours/tours.html'
    context_object_name = 'tour_list'

    def get_queryset(self):
        search_name = self.request.GET.get('search_name')
        search_value = self.request.GET.get('search_value')
        tours = Tour.objects.all()
        if search_name is not None:
            if search_name == "":
                return tours
            selected_tours = tours.filter(name=search_name)
            return selected_tours
        else:
            return tours

class TourCreate(edit.CreateView):
    model = Tour
    fields = ['name', 'description', 'value_adult', 'value_children', 'begin_date', 'end_date', 'places']
    success_url = reverse_lazy('home')


class TourDetail(generic.DetailView):
    model = Tour
    #a = get_flights()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['flights'] = ['1', '2', '3']
        return context


class TourDelete(edit.DeleteView):
    model = Tour
    success_url = reverse_lazy('home')


class TourEdit(edit.UpdateView):
    model = Tour
    fields = ['name', 'description', 'value_adult', 'value_children', 'begin_date', 'end_date', 'places']
    success_url = reverse_lazy('home')

    def get_object(self, queryset=None):
        tour = Tour.objects.get(pk=self.kwargs['pk'])
        return tour


def make_reserve(request, pk):
    # TODO: Do not reserve if already reserved
    user = request.user

    if user.is_authenticated:
        tour = Tour.objects.get(pk=pk)
        profile = Profile(user = user)
        reserves = profile.reserves
        if reserves.filter(id=tour.id).exists():
            messages.add_message(request, messages.INFO, 'Tour Already Reserved')
            return HttpResponseRedirect(reverse_lazy('home'))
        else:
            profile.reserves.add(tour)
            success_url = reverse_lazy('home')
            messages.add_message(request, messages.SUCCESS, 'Tour Reserved')
            return HttpResponseRedirect(reverse_lazy('home'))
    else:
        return HttpResponseRedirect(reverse_lazy('login'))

src/tours/templates/tours/tour_confirm_delete.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}
{{ block.super }}Tours
{% endblock %}

{% block navbar-left %}
{% include "_navbar.html" with active_link="tours" %}
{% endblock %}

{% block navbar-right %}
{% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
{% else %}
{{ block.super }}
{% endif %}
{% endblock %}

{% block container %}
<form method="post">
   {% csrf_token %}
   <p>Are you sure you want to delete "{{ object }}"?</p>
   <input type="submit" value="Confirm" class="btn btn-primary"/>
</form>
{% endblock %}

src/tours/templates/tours/tour_detail.html
{% extends "base.html" %}

{% block title %}
{{ block.super }}Tour {{ tour.name }}
{% endblock %}

{% block navbar-left %}
{% include "_navbar.html" with active_link="tours" %}
{% endblock %}

{% block navbar-right %}
{% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
{% else %}
{{ block.super }}
{% endif %}
{% endblock %}

{% block splash %}
{% endblock %}

{% block container %}
<div class="container">
   <div class="panel panel-default" >
      <div class="panel-heading" >
         <h2>{{ tour.name }}: </h2>
      </div>
      <div class="panel-body">
         <p><h4>Description:</h4>{{ tour.description }}</p>
         <p><h4>Begin Date:</h4> {{ tour.begin_date | date }}</p>
         <p><h4>End Date:</h4> {{ tour.end_date | date }}</p>
         <p><h4>Price:</h4> {{ tour.value_adult }}</p>
         <p><h4>Places visited:</h4> </p>
         <ol>
            {% for place in tour.places.all %}
            <li><p>{{ place.name }}</p>
               {% endfor %}
         </ol>
      </div>
      <div class="panel-footer text-center" >
      {% if user.is_authenticated %}
         <button id="reserve" type="button" class="btn btn-primary btn-group" data-toggle="modal" data-target="#modal_reserve">Reserve</button>
         {% if user.is_staff %}
         <form class="btn-group" action="{% url 'tours:edit' tour.id %}" method="post">
            <input type="submit" value="Edit" class="btn btn-primary">
            {% csrf_token %}
         </form>
         <form class="btn-group" action="{% url 'tours:delete' tour.id %}" method="post">
            <input type="submit" value="Delete" class="btn btn-primary">
            {% csrf_token %}
         </form>
         {% endif %}
      {% else %}
         <a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
         <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
      {% endif %}
      </div>
   </div>
</div>
<p id="jqtest"></p>
<div id="modal_reserve" class="modal fade" role="dialog">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h2 class="modal-title">Reserve {{tour.name}}?</h2>
         </div>
         <div class="modal-body">
            <p><h4>Value of Adult:</h4>R$ {{ tour.value_adult }}</p>
            <p><h4>Value of Children:</h4>R$ {{ tour.value_children }}</p>
            <form class="form-inline form-horizontal">
               <p><h4>Number of passengers:</h4></p>
               <div class="input-group">
                  <span class="input-group-addon">Adults:</span>
                  <input id="but-adult" type="number" class="form-control" placeholder="Adults" />
               </div>
               <div class="input-group" >
                  <span class="input-group-addon">Children:</span>
                  <input id="but-children" type="number" class="form-control" placeholder="Children" />
               </div>
            </form>
            <div class="checkbox">
               <label><input type="checkbox" id="buy_flights">Buy Plane Tickets</label>
            </div>
            <div style="display:none" id="flights">
               <p>Flights</p>
               {% for f in flights %}
               <p>{{ f }}</p>
               {% endfor %}
            </div>
            <p><h4>Total Price:</h4> <div id="price">R$ {{ tour.price }}</div></p>
         </div>
         <div class="modal-footer">
            <form class="btn-group" action="{% url 'tours:reserve' tour.id%}" method="post">
               {% csrf_token %}
               <input type="submit" value="Reserve" class="btn btn-primary">
            </form>
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
         </div>
      </div>
   </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
   $(function(){
      $("input[type='number']").on('click change keyup keydown', function(){
         value_adult = "{{ tour.value_adult }}" * 1;
         value_child = "{{ tour.value_children }}" * 1;
         qnt_adult = $("#but-adult").val();
         qnt_child = $("#but-children").val();
         value = value_adult*qnt_adult + value_child*qnt_child
         $("#price").text("R$ " + value)
         console.log('children: ', qnt_child);
         console.log('adults: ', qnt_adult);
      });
      $('#buy_flights').click(function(){
         $('#flights').toggle(this.checked)
      });
   });
</script>
{% endblock %}

src/tours/templates/tours/tour_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}{{tour.name}}Create Tour{% endblock %}
{% block navbar-left %}
{% include "_navbar.html" with active_link="tours" %}
{% endblock %}

{% block navbar-right %}
{% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
{% else %}
{{ block.super }}
{% endif %}
{% endblock %}

{% block splash %}
{% endblock %}

{% block container %}
<div class="container" >
   <form method="post">
      <div class="form-group" >
         {% csrf_token %}
         {% crispy form %}
         <input type="submit" value="Save" class="btn btn-primary"/>
      </div>
   </form>
</div>
{% endblock %}

src/tours/templates/tours/tour_update_form.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}
{{ block.super }}Tours
{% endblock %}

{% block navbar-left %}
{% include "_navbar.html" with active_link="tours" %}
{% endblock %}

{% block navbar-right %}
{% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
{% else %}
{{ block.super }}
{% endif %}
{% endblock %}

{% block container %}
<form method="post">
   <div class="form-group" >
   {% csrf_token %}
   {% crispy form %}
   <input type="submit" value="Update" class="btn btn-primary"/>
   </div>
</form>
{% endblock %}

src/tours/templates/tours/tours.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}
{{ block.super }}Tours
{% endblock %}

{% block navbar-left %}
{% include "_navbar.html" with active_link="tours" %}
{% endblock %}

{% block navbar-right %}
{% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
{% else %}
{{ block.super }}
{% endif %}
{% endblock %}

{% block container %}
<div class="container-fluid">
   <div class="row" >
         <div class="col-sm-2 text-center" >
      <div class="panel panel-default">
         <div class="panel-heading">
            <h5>Filters</h5>
         </div>
            <form type="get" action=".">
               <div class="panel-body">
               <p><input type="text" id="search_name" name="search_name" placeholder="Search by Name" class="form-control"/></p>
               <p><input type="text" id="search_value" name="search_value" placeholder="Search by Value" class="form-control"/></p>
               </div>
               <div class="panel-footer">
               <p><button type="submit" id="search_name"  class="btn btn-primary">
                     Search <span class="glyphicon glyphicon-search"></span>
                  </button>
               </p>
               </div>
            </form>
         </div>
      </div>
      <div class="col-sm-10 text-center" >
         <div class="panel panel-default" >
            <div class="panel-heading"> <h1>Tours: </h1> </div>
            <ul class="list-group">
               <div class="panel-body">
                  <div class="col-sm-12">
                     {% for tour in tour_list %}
                     <div class="col-sm-6">
                        <a href="{% url 'tours:tour' tour.id %}" class="list-group-item">
                           <h2>{{tour.name}}</h2>
                           <p><b>Price:</b> R$ {{tour.value_adult}}</p>
                           <p><b>Begin:</b> {{ tour.begin_date }} <b>End:</b> {{ tour.end_date }}</p>
                        </a>
                     </div>
                     {% empty %}
                     <li class="list-group-item"><p>No tours</p></li>
                     {% endfor %}
                  </div>
               </div>
            </ul>
            {% if user.is_staff %}
            <div class="panel-footer" >
               <form class="btn-group"action="{% url 'tours:create_tour' %}" >
                  <input type="submit" value="Create Tour" class="btn btn-primary"/>
               </form>
                  <form class="btn-group"action="#" >
                     <input type="submit" value="Create Place" class="btn btn-primary"/>
                  </form>
            </div>
               {% endif %}
         </div>
      </div>
   </div>
</div>
{% endblock %}